### ISSUE TITLE
RemActDate attribute rule preventing creation of MIT record

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-attribute-rules#120]
Hello,
I might have found an issue with the RemActDate attribute rule while doing some testing in the UIC Development server. After creating a facility and a well, I attempted to add a new MIT record to the newly created well. This add attempt failed (see images below) and I was unable to add an MIT record to the well. I was given the script error message: MITRemActDate may not be empty if MITRemediationAction has a value other than ‘waiting’. 
![image](https://user-images.githubusercontent.com/49735267/89676123-53304880-d8a8-11ea-8150-c80d5d91d437.png)
![image](https://user-images.githubusercontent.com/49735267/89676161-6511eb80-d8a8-11ea-9230-e5b85ba930ae.png)
The RemActDate rule seems to be preventing the creation of a new MIT record for a well by triggering before the record can be created. It looks to me like the RemActDate is triggering based on a field within the MIT record even though the record hasn’t been created yet. I’m not sure if this is related to the above issue, but we requested some adjustments to the MITRemActDate attribute rule back in December via issue #119 . Please let me know if you need any additional information.
Thank you

**Comment by steveoh** [comment]
> The RemActDate rule seems to be preventing the creation of a new MIT record for a well by triggering before the record can be created.

You would think this is the case but I have brought this issue up with esri since it causes issues like this. The right click add new to relationship dialog inserts an empty record and then updates the record with the foreign key relationship values. This fouls up the insert/update rules. 

What candace and I typically do in these cases is remove the insert trigger and let the update handle everything. 

Do you want to edit the [RemActDate](https://github.com/uic-utah/uic-attribute-rules/blob/4043f8b1c8a24ae557b320c16649f615e9d5f86c/src/rules/mit.py#L38) rule to only be an update trigger?

**Comment by rsparker-utah** [comment]
Good Morning Steve,
Thank you for the background info and explanation. It sounds like removing the insert trigger and letting the update trigger handle everything is a good solution. Yes let’s edit the RemActDate rule to only be an update trigger in pro. Is there anything I need to advise editors (primarily Brianna) to be aware of with this adjustment or will it be business as usual?

**Comment by steveoh** [comment]
I think it should be ok. The only issue is that you can now insert incomplete records.

**Comment by rsparker-utah** [comment]
Ok, I'll pass that information along to Brianna so that she is aware.

**Comment by rsparker-utah** [comment]
Hi @steveoh I've removed the insert trigger from the RemActDate constraint via ArcPro. Your help was much appreciated, thank you.

**Comment by steveoh** [comment]
Great, I will close this with an update to the source code to match.
