### ISSUE TITLE
UIC Zip Code Domain Error

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-attribute-rules#121]
Hello,
Brianna has found an issue with zip codes in the UIC gdb. She reported the following to me this morning "Zip codes in the database are automatically generated when creating a facility, but I don't think this one (84009) is included in our zip code domains because it's not on the drop down list and it comes up red like an error.  See below.  I've been having to select something else when this zip code comes up to get past the error. "
![UIC_zip_code_error](https://user-images.githubusercontent.com/49735267/105748910-f9781500-5eff-11eb-9d1b-027acef0492b.png)

Please let me know if you need any additional information.

Thank you

**Comment by nathankota** [comment]
yes, it looks like 84009 is not in the domain table

![image](https://user-images.githubusercontent.com/15659642/105754897-d487a000-5f07-11eb-9129-d01d85d2e0ae.png)

**Comment by nathankota** [comment]
84009 zip code added to the `UICZip5Domain`. @rsparker-utah  please confirm and check for any other missing zip codes.

**Comment by Brianna81** [comment]
Thanks guys! I think there might be one more that I've noticed is missing.  I'm pretty sure I wrote it down, but it's in my office. 
 Whenever I get back there (hopefully next week) to find it I'll let you know.

**Comment by nathankota** [comment]
Thanks for confirming. I will close this issue now and if there are others they can be easily added to the domain. Happy to walk you and/or Ryan through that.
