### ISSUE TITLE
Contact Table; OwnerType AR Update

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-attribute-rules#122]
Currently, the “OwnerType” attribute rule for the "ContactType" field on the UDEQ.UICADMIN.UICContact table is allowing the following values (tested in both the dev and prod instances): 

- Owner/Operator
- Owner
- Operator

The following adjustments need to be made to this attribute rule:

1. Operator needs to be removed from the above list
2. Legal Representative needs to be added to the above list to match what is in the new UIC web form application; see also uic-inventory issue [#53](https://github.com/uic-utah/uic-inventory/issues/53) for reference.

With the above changes, the acceptable ContactTypes for the “OwnerType” attribute rule on the UDEQ.UICADMIN.UICContact table should be as follows: 

- Owner/Operator
- Owner
- Legal Representative

I believe this is the associated Arcade script: [contactType.js](https://github.com/uic-utah/uic-attribute-rules/blob/master/src/rules/arcade/contact/contactType.js)

Thank you!

**Comment by nathankota** [comment]
@steveoh Am I thinking correctly that it is simply changing the `ownerTypes` list from `[1, 2, 3]` to `[1, 2, 5]`, and updating the `errorMessage` a little bit?

![image](https://user-images.githubusercontent.com/15659642/157499204-1f66c7ba-2948-4e9f-8f82-05a4992fb156.png)


![image](https://user-images.githubusercontent.com/15659642/157499139-2f8a086c-e9e7-4aba-8958-107e58896955.png)

**Comment by rsparker-utah** [comment]
@nathankota I tried making [this attribute rule update](https://github.com/uic-utah/uic-attribute-rules/pull/123/commits/187b907fc493ee7e2523e96fd4add6bffda47707) in ArcPro; however, ArcPro doesn't seem to let me save the edit unless the "Error Message" field is populated (i.e., the attribute rule is red and the save icon is grayed out). 
![image](https://github.com/uic-utah/uic-attribute-rules/assets/49735267/9be2a7f0-acf8-4c05-9f3e-df865ff2006c)
If I add any text to the "Error Message" dialogue box, the attribute rule will turn green instead of red and the save icon will become available. This "Error Message" dialogue box isn't populated in any of the other attribute rules, so I thought I better consult with you folks first before adding anything (my understanding is that the error message is populated dynamically based on the code in the attribute rule).

For reference, here are the steps I took to attempt to update this attribute rule:

- Ran the reconcile script to update the database
- Ran the delete script to clear versions
- Opened ArcPro
- Selected the UICADMIN connection
- Navigated to the Contact table attribute rules via right clicking the Contact table -> Data design -> attribute rules
- Selected the OwnerType attribute rule
- Adjusted the "var ownerTypes" from  [1, 2, 3] to [1, 2, 5]
- Adjusted the corresponding error message from "There is no owner or operator contact type for this facility." to "There is no owner, owner/operator, or legal representative contact type for this facility."

At this point I tried to save, but was unable to because ArcPro was displaying the "Rule requires an error message." message.

**Comment by steveoh** [comment]
This seems like what is needed. I'd put the error message text you have highlighted in the box so the rule updates. Then if you want to keep it synchronized with this project, then create a pull request to update the contactType you have linked in the original message.

**Comment by rsparker-utah** [comment]
Thank you for the guidance. I followed the same steps I outlined above in the dev environment to update the attribute rule and added the error message text to the "Error Message" box in the attribute rule which let me save the rule update. I then recreated the versions and tested the attribute rule. The attribute rule update worked, but I did notice that it is now displaying both an error message and script message when the attribute rule is triggering. For example, before making the update only a script error message would display:
![image](https://github.com/uic-utah/uic-attribute-rules/assets/49735267/788ecab7-6e75-4a20-be1f-49c4fd88d9f4)

Now after making the update, the error message is being displayed in both an error message and script error:
![image](https://github.com/uic-utah/uic-attribute-rules/assets/49735267/7b276b8e-cb90-4b52-afa4-975de2975b70)

The [attribute rule](https://github.com/uic-utah/uic-attribute-rules/blob/master/src/rules/arcade/contact/contactType.js) for this seems to have two separate possible script error messages based the outcome of the "if" statements. If the other script error message (i.e., There are no facilities related to this contact.) triggers, I'm worried that the resulting notification will display conflicting messages. For example, if the "There are no facilities related to this contact." triggers, I'm worried it would display something like:

Error message: There is no owner, owner/operator, or legal representative contact type for this facility.
Script error: There are no facilities related to this contact.

Is this a valid concern? If so, how can the attribute rules be updated without populating this "Error message" box so that there isn't the potential to display conflicting information?

**Comment by rsparker-utah** [comment]
The “OwnerType” attribute rule for the "ContactType" field on the UDEQ.UICADMIN.UICContact table has been update in the UIC geodatabase to allow the following:

    Owner/Operator
    Owner
    Legal Representative

This update was made using ArcPro in both the development and production instances.
